# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'watch-out' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for watch-out

pod 'InstantSearchVoiceOverlay'
end

target 'watch-out WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for watch-out WatchKit App

end

target 'watch-out WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for watch-out WatchKit Extension

end
